from enum import Enum
from pydantic import BaseModel


class ErrorModel(BaseModel):
    detail: str | dict[str, str]


class ErrorCode(str, Enum):
    # =========================
    # REGISTER
    # =========================
    REGISTER_INVALID_PASSWORD = "REGISTER_INVALID_PASSWORD"
    REGISTER_INVALID_EMAIL = "REGISTER_INVALID_EMAIL"
    REGISTER_USER_ALREADY_EXISTS = "REGISTER_USER_ALREADY_EXISTS"
    REGISTER_USERNAME_TAKEN = "REGISTER_USERNAME_TAKEN"
    REGISTER_WEAK_PASSWORD = "REGISTER_WEAK_PASSWORD"
    REGISTER_EMAIL_NOT_ALLOWED = "REGISTER_EMAIL_NOT_ALLOWED"

    # =========================
    # LOGIN
    # =========================
    LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"
    LOGIN_USER_NOT_FOUND = "LOGIN_USER_NOT_FOUND"
    LOGIN_USER_NOT_VERIFIED = "LOGIN_USER_NOT_VERIFIED"
    LOGIN_USER_DISABLED = "LOGIN_USER_DISABLED"
    LOGIN_TOO_MANY_ATTEMPTS = "LOGIN_TOO_MANY_ATTEMPTS"

    # =========================
    # OAUTH
    # =========================
    OAUTH_INVALID_STATE = "OAUTH_INVALID_STATE"
    OAUTH_PROVIDER_ERROR = "OAUTH_PROVIDER_ERROR"
    OAUTH_NOT_AVAILABLE_EMAIL = "OAUTH_NOT_AVAILABLE_EMAIL"
    OAUTH_USER_ALREADY_EXISTS = "OAUTH_USER_ALREADY_EXISTS"
    OAUTH_EMAIL_NOT_VERIFIED = "OAUTH_EMAIL_NOT_VERIFIED"

    # =========================
    # TOKEN / JWT
    # =========================
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"
    TOKEN_INVALID_ISSUER = "TOKEN_INVALID_ISSUER"

    # =========================
    # REFRESH TOKEN
    # =========================
    NO_REFRESH_TOKEN = "NO_REFRESH_TOKEN"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"

    # =========================
    # PASSWORD RESET
    # =========================
    RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"
    RESET_PASSWORD_TOKEN_EXPIRED = "RESET_PASSWORD_TOKEN_EXPIRED"
    RESET_PASSWORD_INVALID_PASSWORD = "RESET_PASSWORD_INVALID_PASSWORD"
    RESET_PASSWORD_SAME_AS_OLD = "RESET_PASSWORD_SAME_AS_OLD"

    # =========================
    # EMAIL VERIFICATION
    # =========================
    VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"
    VERIFY_USER_TOKEN_EXPIRED = "VERIFY_USER_TOKEN_EXPIRED"
    VERIFY_USER_ALREADY_VERIFIED = "VERIFY_USER_ALREADY_VERIFIED"

    # =========================
    # USER UPDATE
    # =========================
    UPDATE_USER_EMAIL_ALREADY_EXISTS = "UPDATE_USER_EMAIL_ALREADY_EXISTS"
    UPDATE_USER_INVALID_PASSWORD = "UPDATE_USER_INVALID_PASSWORD"
    UPDATE_USER_NOT_FOUND = "UPDATE_USER_NOT_FOUND"

    # =========================
    # PERMISSIONS / AUTHZ
    # =========================
    PERMISSION_DENIED = "PERMISSION_DENIED"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    DEFAULT_ROLE_NOT_CONFIGURED = "DEFAULT_ROLE_NOT_CONFIGURED"

    # =========================
    # SECURITY
    # =========================
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY"
    IP_BLOCKED = "IP_BLOCKED"

    # =========================
    # RATE LIMITING
    # =========================
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # =========================
    # GENERAL
    # =========================
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"




    # REGISTER_USER_ALREADY_EXISTS = "REGISTER_USER_ALREADY_EXISTS"
    # OAUTH_NOT_AVAILABLE_EMAIL = "OAUTH_NOT_AVAILABLE_EMAIL"
    # OAUTH_USER_ALREADY_EXISTS = "OAUTH_USER_ALREADY_EXISTS"
    # OAUTH_INVALID_STATE = "OAUTH_INVALID_STATE"
    # LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"
    # LOGIN_USER_NOT_VERIFIED = "LOGIN_USER_NOT_VERIFIED"
    # RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"
    # RESET_PASSWORD_INVALID_PASSWORD = "RESET_PASSWORD_INVALID_PASSWORD"
    # VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"
    # VERIFY_USER_ALREADY_VERIFIED = "VERIFY_USER_ALREADY_VERIFIED"
    # UPDATE_USER_EMAIL_ALREADY_EXISTS = "UPDATE_USER_EMAIL_ALREADY_EXISTS"
    # UPDATE_USER_INVALID_PASSWORD = "UPDATE_USER_INVALID_PASSWORD"
    ACCESS_TOKEN_ALREADY_EXPIRED = "ACCESS_TOKEN_ALREADY_EXPIRED"
    ACCESS_TOKEN_DECODE_ERROR = "ACCESS_TOKEN_DECODE_ERROR"

    # DEFAULT_ROLE_NOT_CONFIGURED = "DEFAULT_ROLE_NOT_CONFIGURED"
    # NO_REFRESH_TOKEN = "NO_REFRESH_TOKEN"

    # # JWT:
    # TOKEN_EXPIRED = "TOKEN_EXPIRED"
    # TOKEN_INVALID = "TOKEN_INVALID"
    # TOKEN_REVOKED = "TOKEN_REVOKED"
    # TOKEN_INVALID_ISSUER = "TOKEN_INVALID_ISSUER"
    # TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"